title: Praise Sabo-Wada
logo: /Users/admin/Downloads/Praise.heic
description: A data analyst with vast amounts of technical knowledge and experience.
#show_downloads: false
theme: jekyll-theme-minimal
